permalink: /:title

# Site authors
# append to list whenever an author is added
author:
  - name: NAIFA

# ------------------------------------------------------
# Site wide - Do not alter unless you know what you're doing
# ------------------------------------------------------
title: NAIFA of Greater Harrisburg
email:
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "/"
logo: /images/naifagh-logo.jpg
footerlogo: /images/footer-logo.png
twitter_username: naifahbg
github_username:  naifahbg
join_url: https://member.naifa.org/Services/NAIFA/Join/NAIFA/Join.aspx

# NAIFA
naifa: NAIFA of Greater Harrisburg
naifa_short: NAIFA
naifa_url: www.naifahbg.com
naifa_address: 600 N. Front St., Wormleysburg, PA 17043
naifa_phone: 717-745-8027
naifa_email: naifaghbg@gmail.com
naifa_copyright: NAIFA-Greater Harrisburg. All rights reserved.

# See into the future
future: true

# SASS
sass:
  style: compressed

exclude:
  - build.cmd
  - Gemfile
  - Gemfile.lock
  - README.md
  - jekyll-run.cmd

# Social - NAIFA social accounts
social_links:
  - service: comment
    # url: https://www.naifahbg.com/
  - service: twitter
    # url: https://twitter.com/naifahbg
  - service: facebook-official
    # url: https://www.facebook.com/naifahbg
  - service: youtube-play
    # url: https://www.youtube.com/user/naifahbg
  - service: linkedin
    # url: https://www.linkedin.com/company/naifahbg
